# Generated by Django 5.1.3 on 2024-11-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_ip_address_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='longitude',
        ),
    ]
