# Generated by Django 5.1.3 on 2024-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_latitude_remove_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
