# Generated by Django 5.1.3 on 2024-11-15 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_pictures/')),
                ('name', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=50)),
                ('temp_address', models.TextField(verbose_name='Temporary Address')),
                ('perm_address', models.TextField(verbose_name='Permanent Address')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10)),
                ('post', models.CharField(max_length=50)),
                ('citizenship_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('parent_name', models.CharField(max_length=255)),
                ('citizenship_no', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=100)),
                ('incident_time', models.TimeField()),
                ('incident_date', models.DateField()),
                ('incident_description', models.TextField()),
                ('sound_recorder', models.FileField(blank=True, null=True, upload_to='sound_recordings/')),
                ('evidence_1', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('evidence_2', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('evidence_3', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('evidence_4', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=10)),
                ('tole_name', models.CharField(max_length=100)),
                ('front_citizenship', models.ImageField(blank=True, null=True, upload_to='citizenship/')),
                ('back_citizenship', models.ImageField(blank=True, null=True, upload_to='citizenship/')),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='birth_certificates/')),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
