# Generated by Django 5.1.3 on 2024-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_ip_address_delete_userlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('citizenship_no', models.CharField(max_length=50)),
                ('licence_no', models.CharField(max_length=50)),
                ('bought_from', models.CharField(max_length=255)),
                ('engine_no', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('transpo_type', models.CharField(choices=[('Two-Wheeler', 'Two-Wheeler'), ('Four-Wheeler', 'Four-Wheeler'), ('Heavy Vehicle', 'Heavy Vehicle')], max_length=20)),
                ('bought_date', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('ward', models.IntegerField()),
                ('tole_name', models.CharField(max_length=100)),
                ('front_citizenship', models.ImageField(upload_to='documents/citizenship/front/')),
                ('back_citizenship', models.ImageField(upload_to='documents/citizenship/back/')),
                ('user_photo', models.ImageField(upload_to='documents/user_photos/')),
                ('vehicle_papers', models.FileField(blank=True, null=True, upload_to='documents/vehicle_papers/')),
                ('vehicle_front_photo', models.ImageField(upload_to='vehicles/photos/front/')),
                ('vehicle_back_photo', models.ImageField(upload_to='vehicles/photos/back/')),
                ('vehicle_left_photo', models.ImageField(upload_to='vehicles/photos/left/')),
                ('vehicle_right_photo', models.ImageField(upload_to='vehicles/photos/right/')),
            ],
        ),
    ]
