# Generated by Django 5.1.3 on 2024-11-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_crimereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrimeReport',
        ),
    ]
